[package]
name = "notion-generator-bin"
description = "Takes in a Notion page and turns it into an HTML page!"
version = "0.1.3"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.57"

[dependencies]
anyhow = { version = "1" }
clap = { version = "3.0.0-rc.1", features = ["derive"] }
notion-generator = { path = "../" }
reqwest = { git = "https://github.com/Mathspy/reqwest", branch = "impl-service-for-client", default-features = false }
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }

[[bin]]
name = "notion-generator"
path = "src/main.rs"
