[package]
name = "notion-generator"
description = "Takes in a Notion page and turns it into an HTML page!"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }

[dev-dependencies]
pretty_assertions = { version = "1" }
