name: Continuous Integration

on:
  push:
    tags:
      - "v*" # Version tagged pushes
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Are you happy Clippy?
        run: cargo clippy

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Running tests
        run: cargo test

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [clippy, test]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --release

      - name: Display checksum
        run: shasum -a 256 target/release/notion-generator

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/notion-generator
          generate_release_notes: true
